example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import catalog_display

app_name = 'katalog'

urlpatterns = [
    path('',catalog_display,name='show_catalog')
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_json
from mywatchlist.views import show_xml
from mywatchlist.views import show_html

app_name = 'mywatchlist'


urlpatterns = [
    path('',show_mywatchlist, name='mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/',show_html, name='show_html')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from todolist.views import *
from django.urls import path
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task') 
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    have_watched = models.TextField() #booleanfield
    movie_title = models.TextField() #charfield
    movie_rating = models.IntegerField() #bisa di max ke 5
    movie_release = models.IntegerField() #datefield
    movie_review = models.TextField()

todolist/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

def catalog_display(request):
    data_item_catalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_item_catalog,
        'name': 'Ammar Ash Shiddiq',
        'npm': '2106656560'
    }
    return render(request, 'katalog.html', context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.


def show_mywatchlist(request):
    data_mywatchlist = MyWatchList.objects.all()
    context = {
    'watch_list' : data_mywatchlist,
    'name' : 'Ammar Ash Shiddiq',
    'npm': '2106656560'
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data_mywatchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data_mywatchlist), content_type="application/xml")

def show_json(request):
    data_mywatchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data_mywatchlist), content_type="application/json")

def show_html(request):
    data_mywatchlist = MyWatchList.objects.all()
    context = {
    'watch_list' : data_mywatchlist,
    'name' : 'Ammar Ash Shiddiq',
    'npm': '2106656560'
    }
    return render(request, "mywatchlist.html", context)

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import Task
# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_data = Task.objects.filter(user=request.user)
    context = {'todolist': todolist_data,
                'username': request.user,      
                # ask why last_login doesn't work
                # 'last_login': request.COOKIES['last_login'],
                }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    return render(request, "create_task.html")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')

    context = {'form':form}
    return render(request, 'reg1ster.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'log1n.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
      <th>{{barang.item_name}}</th>
      <th>{{barang.item_price}}</th>
      <th>{{barang.item.stock}}</th>
      <th>{{barang.description}}</th>
      <th>{{barang.rating}}</th>
      <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style="text-align:center">🙏 Assignment 3 PBP/PBD 🙏</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</Title></th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in watch_list %}
        <tr>
            <th>{{item.have_watched}}</th>
            <th>{{item.movie_title}}</th>
            <th>{{item.movie_rating}}</th>
            <th>{{item.movie_release}}</th>
            <th>{{item.movie_review}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'create_task.css'%}">

<h1>Add New Task</h1>
<div class="center m-5">
    <form method="post">
        {% csrf_token %}
            <tr>
                <td>Title: </td>
                <td><input type="text" name="title" placeholder="Fill todo" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input type="text" name="description" placeholder="fill description" class="form-control"></td>
            </tr>
    
        <br>
        <button type="submit">Create Task</button>
    </form>
</div>
    
    {% endblock %}

todolist/templates/log1n.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'log1n.css'%}">
{% endblock meta %}

{% block content %}

<div class="login-box">
    <h2>Login</h2>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="user-box">
            <input type="text" name="username" class="form-control" placeholder="Username">
            <label>Username</label>
        </div>
        <div class="user-box">
            <input type="password" name="password" class="form-control" placeholder="Password">
            <label>Password</label>
        </div>

        <div class="button-form">
            <tr>
                <td></td>
                <td><input style="color:white" class="btn login_btn" type="submit" value="Login"></td>
            </tr>
            <div id="register">
                Don't have an account ?
                <a href="{% url 'todolist:register' %}">
                    Register
                </a>
            </div>

        </div>

    </form>
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>

{% endblock meta %}

{% block content %}

<div class = "login">

    <h1 style='color:Tomato'>Login</h1>
    <img src="https://cdn.discordapp.com/attachments/900746236825571348/1024880541658525766/password.JPG" alt="Login" style="width:200px;height:200px;">
    <form method="POST" action="">
        {% csrf_token %}
        <table style="border:1px solid rgba(131, 3, 223, 0.636)">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Don't have an account? <a href="{% url 'todolist:register' %}">Create Account</a>

</div>

{% endblock content %}

todolist/templates/reg1ster.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
<link rel="stylesheet" href="{% static 'register.css'%}">
{% endblock meta %}

<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">

{% block content %}

<div class="testbox">
  <h1>Registration</h1>

  <form action="/" method="POST">
    {% csrf_token %}
  <hr>
    <label id="icon" for="name"><i class="icon-envelope "></i></label>
    <input type="text" name="name" id="name" placeholder="Username" required/>
    <label id="icon" for="name"><i class="icon-user"></i></label>
    <input type="password" name="name" id="name" placeholder="Password" required/>
    <label id="icon" for="name"><i class="icon-shield"></i></label>
    <input type="password" name="name" id="name" placeholder="Password Confirmation" required/>

    <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Register"/></td>
    </tr>
  </form>
  {% if messages %}
  <ul>
      {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
  </ul>
{% endif %}
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<div class = "login">
    <h1>Registration Form</h1>

        <form method="POST" >
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register"/></td>
                </tr>
            </table>
        </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

todolist/templates/todo1ist.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'todo1ist.css'%}">
{% block content %}
<div class="listBox">
    <ul>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>Google</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>Airbnb</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>twitter</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>Lystable</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>Facebook</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
      <li>
        <div class="listImg"></div>
        <dl>
          <dt>Apple</dt>
          <dd>
            <p>Operation Manager</p>
            <span>May 12 - Sep 15</span>
          </dd>
        </dl>
      </li>
    </ul>  
  </div>
  <p class="by">Design by <a href="https://dribbble.com/shots/2316230-Lystable-Landing-Page" target="_blank">dribbble</a></p>
  
  
  {% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
 {% block content %}
 <style>
    h1,h2,h3,b, button, th, td, table {text-align: center;}
    table, th, td {
        border-collapse: collapse;
        border:1px solid black;
        border-width: 1px;
    
    }
    *{
      text-align: center;
      vertical-align: middle;
    }
    th, td {
      padding: 10px 10px
    }
    table,button {
      margin-left: auto;
      margin-right: auto;
    }
  </style>

 <h1> Welcome to {{username}}'s Todolist </h1>

  {% for task in todolist %}
 <div class="card">
  <div class="card-header">
    {{task.date}}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{task.title}}</h5>
    <p class="card-text">{{task.description}}</p>
  </div>
</div>
  {% endfor %}


 <!-- <table>
   <tr>
     <th>Date</th>
     <th>Title</th>
     <th>Description</th>
   </tr>
     {% for task in todolist %}
     
     <tr>
         <td>{{task.date}}</td>
         <td>{{task.title}}</td>
         <td>{{task.description}}</td>
         {% endfor %}
     </tr>
 </table> -->
<br>
<h5>Last Login: {{ last_login }}</h5>
<ul>
  <button><a href="{% url 'todolist:create_task' %}">Create Task</a></button>
  <button><a href="{% url 'todolist:logout' %}">Logout</a></button>
</ul>


{% endblock content %}